### ISSUE TITLE
Use manager to install local developed plugin

### ISSUE THREAD

**Issue by luanabeckerdaluz** [3liz/qgis-plugin-manager#71]
Hello,

I was wondering if I could use the package to install a plugin from a local folder? 
Perhaps the correct question would be, can I use this manager to replace pb_tool?

Regards,
Luana

**Comment by Gustry** [comment]
I think it works with a local repository (with `file://` instead of `https://`).

But I don't think you need QGIS-Plugin-Manager to work on your plugin. This is not the correct use case for this tool (as you don't have yet the XML repository)
I think you need to create a symlink for instance ?

IMHO, pb_tool is a legacy tool and not needed (I haven't used for more than 10 years). Latest release of PBTool was 10 years ago https://github.com/g-sherman/plugin_build_tool/tags). Latest commit is 6 years ago : https://github.com/g-sherman/plugin_build_tool

I'm closing because it's not the scope of this tool, but you can continue

**Comment by luanabeckerdaluz** [comment]
Hi @Gustry 
Thank you so much for your reply! 

I will try to install with `file://`. In my case, I was using pb_tool to deploy plugin, but the package is old, that's why I was looking for other manager. But I think I can just move the plugin folder to QGIS plugins folder and it will work, since I install requirements.

Thank you for the attention!
Regards,
Luana
